-- Migration: add_ref_task_revenue_rates
-- Source: Revenue Metrics_Duration & Amount (1).xlsx
-- Spec: docs/specs/revenue-rate-sheet.md

CREATE TABLE IF NOT EXISTS reference.ref_task_revenue_rates (
  id              bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  market_bucket   text NOT NULL,
  task_name       text NOT NULL,
  task_name_norm  text NOT NULL,
  duration_hrs    numeric(5,2) NOT NULL,
  amount_usd      numeric(10,2) NOT NULL,
  source_file     text,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now(),
  UNIQUE (market_bucket, task_name)
);

CREATE INDEX IF NOT EXISTS idx_revenue_rates_market
  ON reference.ref_task_revenue_rates(market_bucket);
CREATE INDEX IF NOT EXISTS idx_revenue_rates_task_norm
  ON reference.ref_task_revenue_rates(task_name_norm);

INSERT INTO reference.ref_task_revenue_rates (market_bucket, task_name, task_name_norm, duration_hrs, amount_usd, source_file) VALUES
  ('VZW Embedded / Macro', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 1, 80, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', '48Hr / Test Package Live Review Complete', '48Hr / Test Package Live Review Complete', 1, 55, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', '48Hr / Test Package Revision Complete 2', '48Hr / Test Package Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', '48Hr / Test Package Revision Complete 3', '48Hr / Test Package Revision Complete 3', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'COP Revision Complete', 'COP Revision Complete', 0.5, 30, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'COP Revision Complete 3', 'COP Revision Complete 3', 0.2, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'COP Revision Complete 4', 'COP Revision Complete 4', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'COP Upload Complete', 'COP Upload Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.3, 21, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Day 1 Package Complete', 'Day 1 Package Complete', 0.7, 49, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Day 1 Package Revision Complete', 'Day 1 Package Revision Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Day 1 Package Revision Complete 2', 'Day 1 Package Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Final COP Complete', 'Final COP Complete', 2.5, 100, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Live Review Complete', 'Live Review Complete', 3.5, 200, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Live Review Complete 2', 'Live Review Complete 2', 1.5, 83, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Live Review Complete 3', 'Live Review Complete 3', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'LL COP Complete', 'LL COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'LL COP Rejections-Caused Revision Complete', 'LL COP Rejections-Caused Revision Complete', 0.3, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'LL COP Rejections-Caused Revision Complete 2', 'LL COP Rejections-Caused Revision Complete 2', 0, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'LL COP Revision Complete', 'LL COP Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'LL COP Revision Complete 2', 'LL COP Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'PMI COP Complete', 'PMI COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'PMI COP Rejections Reviewed', 'PMI COP Rejections Reviewed', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'PMI COP Rejections Reviewed 2', 'PMI COP Rejections Reviewed 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'PMI COP Rejections-Caused Revision Complete', 'PMI COP Rejections-Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'PMI COP Revision Complete', 'PMI COP Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'PMI COP Upload Complete', 'PMI COP Upload Complete', 0.1, 6, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'PMI COP Upload Complete 2', 'PMI COP Upload Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Preliminary Review Complete', 'Preliminary Review Complete', 1.5, 83, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Punch Item Live Review Complete', 'Punch Item Live Review Complete', 1, 55, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Punch Item Live Review Complete 2', 'Punch Item Live Review Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'RF Mitigation COP Complete', 'RF Mitigation COP Complete', 0.3, 21, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'RF Mitigation COP Rejections Reviewed', 'RF Mitigation COP Rejections Reviewed', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'RF Mitigation COP Revision Complete', 'RF Mitigation COP Revision Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'RF Mitigation COP Upload Complete', 'RF Mitigation COP Upload Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.5, 35, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Site Set-Up Revision Complete', 'Site Set-Up Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Site Set-Up Revision Complete 2', 'Site Set-Up Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Embedded / Macro', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 0.7, 61, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', '48Hr / Test Package Revision Complete 2', '48Hr / Test Package Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'COP Revision Complete', 'COP Revision Complete', 0.4, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.4, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'COP Revision Complete 3', 'COP Revision Complete 3', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'COP Revision Complete 4', 'COP Revision Complete 4', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.3, 26, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Day 1 Package Complete', 'Day 1 Package Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Final COP Complete', 'Final COP Complete', 1, 100, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Live Review Complete', 'Live Review Complete', 2, 150, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Live Review Complete 2', 'Live Review Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'LL COP Complete', 'LL COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'LL COP Rejections Reviewed', 'LL COP Rejections Reviewed', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'LL COP Revision Complete', 'LL COP Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'LL COP Revision Complete 2', 'LL COP Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'LL COP Upload Complete', 'LL COP Upload Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'PMI COP Complete', 'PMI COP Complete', 0.3, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'PMI COP Upload Complete', 'PMI COP Upload Complete', 0.1, 6, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Preliminary Review Complete', 'Preliminary Review Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Punch Item Live Review Complete', 'Punch Item Live Review Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'RF Mitigation COP Complete', 'RF Mitigation COP Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.2, 18, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Site Set-Up Revision Complete', 'Site Set-Up Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Site Set-Up Revision Complete 2', 'Site Set-Up Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Small Cell', 'Station Record / In-Service Only Update Complete', 'Station Record / In-Service Only Update Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 1, 3, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'COP Revision Complete', 'COP Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.5, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.3, 1, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Final COP Complete', 'Final COP Complete', 2.5, 75, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'LL COP Complete', 'LL COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'LL COP Revision Complete', 'LL COP Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'LL COP Upload Complete', 'LL COP Upload Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Live Review Complete', 'Live Review Complete', 3.5, 150, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'PMI COP Complete', 'PMI COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'PMI COP Revision Complete', 'PMI COP Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'PMI COP Upload Complete', 'PMI COP Upload Complete', 0.1, 6, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Punch Item Live Review Complete', 'Punch Item Live Review Complete', 1, 55, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.5, 1, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'Site Set-Up Revision Complete', 'Site Set-Up Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'COP Revision Complete 3', 'COP Revision Complete 3', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'PMI COP Rejections Reviewed', 'PMI COP Rejections Reviewed', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/DONOR', 'PMI COP Rejections-Caused Revision Complete', 'PMI COP Rejections-Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/MDU', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/MDU', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/MDU', 'Final COP Complete', 'Final COP Complete', 1, 75, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/MDU', 'Live Review Complete', 'Live Review Complete', 1.5, 70, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/MDU', 'COP Revision Complete', 'COP Revision Complete', 0.3, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AAHI/MDU', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'COP Revision Complete', 'COP Revision Complete', 0.3, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.2, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'Final COP Complete', 'Final COP Complete', 1, 100, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.2, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'Site Set-Up Revision Complete', 'Site Set-Up Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.2, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Ground Scope', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Decom', 'LL COP Complete', 'LL COP Complete', 0.3, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Decom', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.1, 50, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('VZW Decom', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Westell/CGC', 'COP Revision Complete', 'COP Revision Complete', 0, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Westell/CGC', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Westell/CGC', 'Final COP Complete', 'Final COP Complete', 0.5, 50, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Westell/CGC', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.1, 15, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Westell/CGC', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 1, 80, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', '48Hr / Test Package Live Review Complete', '48Hr / Test Package Live Review Complete', 1, 55, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', '48Hr / Test Package Revision Complete 2', '48Hr / Test Package Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Punch Items Received 3', 'COP Punch Items Received 3', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Revision Complete', 'COP Revision Complete', 0.5, 30, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Revision Complete 3', 'COP Revision Complete 3', 0.2, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Revision Complete 4', 'COP Revision Complete 4', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Revision Complete 5', 'COP Revision Complete 5', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Revision Complete 6', 'COP Revision Complete 6', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Upload Complete', 'COP Upload Complete', 0.5, 33, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Upload Complete 2', 'COP Upload Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Upload Complete 3', 'COP Upload Complete 3', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Upload Complete 4', 'COP Upload Complete 4', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'COP Upload Complete 5', 'COP Upload Complete 5', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.3, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Day 1 Package Complete', 'Day 1 Package Complete', 0.7, 46, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Day 1 Package Revision Complete', 'Day 1 Package Revision Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Day 1 Package Revision Complete 2', 'Day 1 Package Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Final COP Complete', 'Final COP Complete', 2.5, 100, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Live Review Complete', 'Live Review Complete', 3.5, 200, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Live Review Complete 2', 'Live Review Complete 2', 1.5, 83, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'LL COP Complete', 'LL COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'LL COP Rejections Reviewed', 'LL COP Rejections Reviewed', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'LL COP Rejections-Caused Revision Complete', 'LL COP Rejections-Caused Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'LL COP Revision Complete', 'LL COP Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'LL COP Revision Complete 2', 'LL COP Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'LL COP Upload Complete', 'LL COP Upload Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Ontel Caused Revision Complete 2', 'Ontel Caused Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'PMI COP Complete', 'PMI COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'PMI COP Revision Complete', 'PMI COP Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Preliminary Review Complete', 'Preliminary Review Complete', 1.5, 83, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Punch Item Live Review Complete', 'Punch Item Live Review Complete', 1, 55, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Punch Item Live Review Complete 2', 'Punch Item Live Review Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Punch Item Live Review Complete 3', 'Punch Item Live Review Complete 3', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Punch Item Live Review Complete 4', 'Punch Item Live Review Complete 4', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Raw Files Received', 'Raw Files Received', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.5, 33, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Site Set-Up Revision Complete', 'Site Set-Up Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', 'Site Set-Up Revision Complete 2', 'Site Set-Up Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', '1. RF Mitigation COP Complete', 'RF Mitigation COP Complete', 0.3, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', '4. RF Mitigation COP Revision Complete', 'RF Mitigation COP Revision Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('AT&T', '6. RF Mitigation COP Rejections Reviewed', 'RF Mitigation COP Rejections Reviewed', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'COP Revision Complete', 'COP Revision Complete', 0.4, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.4, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'COP Upload Complete', 'COP Upload Complete', 0.5, 44, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.2, 18, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Final COP Complete', 'Final COP Complete', 1.5, 75, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'LL COP Complete', 'LL COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'LL COP Revision Complete', 'LL COP Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Live Review Complete', 'Live Review Complete', 3.5, 150, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.2, 18, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Day 1 Package Complete', 'Day 1 Package Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Punch Item Live Review Complete', 'Punch Item Live Review Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Dish Wireless', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 1, 80, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'COP Revision Complete', 'COP Revision Complete', 0.5, 30, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'COP Upload Complete', 'COP Upload Complete', 0.5, 58, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.3, 35, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Final COP Complete', 'Final COP Complete', 2.5, 100, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'LL COP Complete', 'LL COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Live Review Complete', 'Live Review Complete', 3.5, 200, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Punch Item Live Review Complete', 'Punch Item Live Review Complete', 1, 55, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.5, 58, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Site Set-Up Revision Complete', 'Site Set-Up Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'COP Revision Complete 3', 'COP Revision Complete 3', 0.2, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'COP Revision Complete 4', 'COP Revision Complete 4', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'COP Upload Complete 2', 'COP Upload Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'COP Upload Complete 3', 'COP Upload Complete 3', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Punch Item Live Review Complete 2', 'Punch Item Live Review Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', '3rd Party COP Rejections Reviewed', '3rd Party COP Rejections Reviewed', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'LL COP Revision Complete', 'LL COP Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'LL COP Upload Complete', 'LL COP Upload Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', '3rd Party COP Revision Complete', '3rd Party COP Revision Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Day 1 Package Complete', 'Day 1 Package Complete', 0.7, 39, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Live Review Complete 2', 'Live Review Complete 2', 1.5, 83, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'Preliminary Review Complete', 'Preliminary Review Complete', 1.5, 83, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'LL COP Revision Complete 2', 'LL COP Revision Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('TMO', 'LL COP Rejections-Caused Revision Complete', 'LL COP Rejections-Caused Revision Complete', 0.3, 17, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 1, 175, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'Final COP Complete', 'Final COP Complete', 4, 750, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.2, 35, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'COP Punch Items Received 4', 'COP Punch Items Received 4', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'COP Revision Complete', 'COP Revision Complete', 0.5, 40, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.5, 30, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'COP Revision Complete 3', 'COP Revision Complete 3', 0.2, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'COP Revision Complete 4', 'COP Revision Complete 4', 0.2, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'Day 1 Package Complete', 'Day 1 Package Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 1', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 1, 40, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'COP Revision Complete', 'COP Revision Complete', 0.2, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.2, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'COP Revision Complete 3', 'COP Revision Complete 3', 0.2, 5, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'COP Upload Complete', 'COP Upload Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'Day 1 Package Complete', 'Day 1 Package Complete', 0.5, 29, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'Final COP Complete', 'Final COP Complete', 0.5, 150, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0.2, 11, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('FTTH Phase 2', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', '48Hr / Test Package Complete', '48Hr / Test Package Complete', 0.5, 45, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', '48Hr / Test Package Revision Complete', '48Hr / Test Package Revision Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'COP Revision Complete', 'COP Revision Complete', 0.4, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'COP Revision Complete 2', 'COP Revision Complete 2', 0.4, 10, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'COP Upload Complete', 'COP Upload Complete', 0.5, 45, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'COP Upload Complete 2', 'COP Upload Complete 2', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'Data Post-Fill Complete', 'Data Post-Fill Complete', 0.5, 28, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'Data Pre-Fill Complete', 'Data Pre-Fill Complete', 0.2, 18, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'Final COP Complete', 'Final COP Complete', 1.5, 150, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'LL COP Complete', 'LL COP Complete', 0.5, 25, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.2, 18, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'Site Set-Up Revision Complete', 'Site Set-Up Revision Complete', 0, 0, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('USCC', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Gulf Services', 'Site Set-Up Complete', 'Site Set-Up Complete', 0.2, 20, 'Revenue Metrics_Duration & Amount (1).xlsx'),
  ('Gulf Services', 'Ontel Caused Revision Complete', 'Ontel Caused Revision Complete', 0.5, 20, 'Revenue Metrics_Duration & Amount (1).xlsx');
