-- Migration 048: Timer entry additions table + rebuild function update
--
-- Techs occasionally forget to start/stop the timer and need an entry added
-- for a past day after the fact. The Swift API is the source of truth for
-- raw entries and we cannot backfill into it. Corrections and removals only
-- modify existing entries.
--
-- This migration adds `stg_timer_entry_additions` as the third correction
-- channel: parallel to stg_timer_corrections and stg_timer_entry_removals.
-- rebuild_timer_clean() is updated to UNION additions into the clean table
-- after applying corrections.
--
-- Id space: additions get ids starting at 10_000_000_000_000 (10 trillion)
-- to avoid collision with stg_timer_activities.id when both are merged into
-- stg_timer_activities_clean during rebuild. Activities ids are in the
-- low millions today — well below the offset.

-- =========================================================================
-- 1. Create stg_timer_entry_additions
-- =========================================================================
CREATE TABLE IF NOT EXISTS data_staging.stg_timer_entry_additions (
    id              BIGINT PRIMARY KEY
                      GENERATED BY DEFAULT AS IDENTITY
                      (START WITH 10000000000000 INCREMENT BY 1),
    entry_id        TEXT UNIQUE,   -- 12-char md5 hash (same algorithm as corrections)

    -- Mirror stg_timer_activities columns
    project         TEXT,
    project_number  INTEGER,
    project_did     TEXT NOT NULL,
    site_name       TEXT,
    site_id         TEXT,
    task            TEXT,
    task_clean      TEXT,
    site_lat        NUMERIC,
    site_long       NUMERIC,
    user_lat        NUMERIC,
    user_long       NUMERIC,
    user_accuracy_m NUMERIC,
    site_vs_user_km NUMERIC,
    start_time      TIMESTAMPTZ NOT NULL,
    end_time        TIMESTAMPTZ,
    duration_min    NUMERIC,
    user_name       TEXT,
    user_email      TEXT NOT NULL,
    user_role       TEXT,
    run_id          UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
    run_date        DATE NOT NULL DEFAULT CURRENT_DATE,
    start_date      DATE,
    end_date        DATE,
    loaded_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Additions-specific metadata
    reason          TEXT,
    added_by        TEXT,
    added_at        TIMESTAMPTZ DEFAULT NOW(),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_timer_entry_additions_natural_key
    ON data_staging.stg_timer_entry_additions (project_did, user_email, start_time);

CREATE INDEX IF NOT EXISTS idx_timer_entry_additions_user_date
    ON data_staging.stg_timer_entry_additions (user_email, start_date);

-- =========================================================================
-- 2. Update rebuild_timer_clean() to include manual additions
-- =========================================================================
CREATE OR REPLACE FUNCTION data_staging.rebuild_timer_clean()
RETURNS void
LANGUAGE plpgsql
SET statement_timeout = '300s'
AS $$
BEGIN
    TRUNCATE TABLE data_staging.stg_timer_activities_clean;

    -- Step 1: Insert from staging, excluding rejected duplicates + removals
    -- (unchanged from migration 042)
    INSERT INTO data_staging.stg_timer_activities_clean
    SELECT DISTINCT ON (
        t.project_did, t.user_email, t.start_time, t.site_name, t.site_id,
        t.task, t.end_time, t.duration_min
    ) t.*
    FROM data_staging.stg_timer_activities t
    WHERE
        -- Exclude rows matching rejected natural keys from resolved reviews
        NOT EXISTS (
            SELECT 1
            FROM data_staging.stg_timer_duplicate_reviews r,
                 jsonb_array_elements(r.rejected_entries) rej
            WHERE r.status IN ('resolved', 'auto_resolved')
              AND r.rejected_entries IS NOT NULL
              AND t.project_did = r.project_did
              AND t.user_email  = r.user_email
              AND t.start_time  = r.start_time
              AND t.site_name IS NOT DISTINCT FROM r.site_name
              AND t.site_id   IS NOT DISTINCT FROM r.site_id
              AND t.task      IS NOT DISTINCT FROM r.task
              AND t.end_time IS NOT DISTINCT FROM (rej->>'end_time')::timestamptz
              AND t.duration_min IS NOT DISTINCT FROM (rej->>'duration_min')::numeric
        )
        -- For unresolved duplicates, keep only the entry with the latest end_time
        AND NOT EXISTS (
            SELECT 1
            FROM data_staging.stg_timer_duplicate_reviews r,
                 jsonb_array_elements(r.entries) e
            WHERE r.status IN ('pending', 'notified')
              AND t.project_did = r.project_did
              AND t.user_email  = r.user_email
              AND t.start_time  = r.start_time
              AND t.site_name IS NOT DISTINCT FROM r.site_name
              AND t.site_id   IS NOT DISTINCT FROM r.site_id
              AND t.task      IS NOT DISTINCT FROM r.task
              AND t.end_time IS NOT DISTINCT FROM (e->>'end_time')::timestamptz
              AND t.duration_min IS NOT DISTINCT FROM (e->>'duration_min')::numeric
              AND (e->>'end_time')::timestamptz < (
                  SELECT MAX((e2->>'end_time')::timestamptz)
                  FROM jsonb_array_elements(r.entries) e2
              )
        )
        -- Exclude removed entries UNLESS reverted or overridden by correction
        AND NOT EXISTS (
            SELECT 1
            FROM data_staging.stg_timer_entry_removals rm
            WHERE t.project_did = rm.project_did
              AND t.user_email  = rm.user_email
              AND t.start_time  = rm.start_time
              AND t.site_name IS NOT DISTINCT FROM rm.site_name
              AND t.site_id   IS NOT DISTINCT FROM rm.site_id
              AND t.task      IS NOT DISTINCT FROM rm.task
              AND t.end_time IS NOT DISTINCT FROM rm.end_time
              AND t.duration_min IS NOT DISTINCT FROM rm.duration_min
              AND rm.reason IS DISTINCT FROM 'REVERTED'
              AND NOT EXISTS (
                  SELECT 1
                  FROM data_staging.stg_timer_corrections c
                  WHERE c.project_did = rm.project_did
                    AND c.user_email  = rm.user_email
                    AND c.start_time  = rm.start_time
                    AND c.site_name IS NOT DISTINCT FROM rm.site_name
                    AND c.site_id   IS NOT DISTINCT FROM rm.site_id
                    AND c.task      IS NOT DISTINCT FROM rm.task
                    AND c.end_time IS NOT DISTINCT FROM rm.end_time
                    AND c.original_duration_min IS NOT DISTINCT FROM rm.duration_min
              )
        )
    ORDER BY t.project_did, t.user_email, t.start_time, t.site_name, t.site_id,
             t.task, t.end_time, t.duration_min, t.id;

    -- Step 2: Apply duration corrections (unchanged)
    UPDATE data_staging.stg_timer_activities_clean t
    SET duration_min = c.corrected_duration_min,
        end_time    = c.corrected_end_time
    FROM data_staging.stg_timer_corrections c
    WHERE c.status = 'corrected'
      AND t.project_did = c.project_did
      AND t.user_email  = c.user_email
      AND t.start_time  = c.start_time
      AND t.site_name IS NOT DISTINCT FROM c.site_name
      AND t.site_id   IS NOT DISTINCT FROM c.site_id
      AND t.task      IS NOT DISTINCT FROM c.task
      AND t.end_time IS NOT DISTINCT FROM c.end_time
      AND t.duration_min IS NOT DISTINCT FROM c.original_duration_min;

    -- Step 3 (NEW): Append manual additions.
    -- Column list is explicit so it stays stable if stg_timer_activities ever gains columns.
    INSERT INTO data_staging.stg_timer_activities_clean (
        id, project, project_number, project_did, site_name, site_id,
        task, task_clean, site_lat, site_long, user_lat, user_long,
        user_accuracy_m, site_vs_user_km, start_time, end_time, duration_min,
        user_name, user_email, user_role,
        run_id, run_date, start_date, end_date, loaded_at
    )
    SELECT
        a.id, a.project, a.project_number, a.project_did, a.site_name, a.site_id,
        a.task, a.task_clean, a.site_lat, a.site_long, a.user_lat, a.user_long,
        a.user_accuracy_m, a.site_vs_user_km, a.start_time, a.end_time, a.duration_min,
        a.user_name, a.user_email, a.user_role,
        a.run_id, a.run_date,
        COALESCE(a.start_date, (a.start_time AT TIME ZONE 'America/New_York')::date),
        COALESCE(a.end_date,   (a.start_time AT TIME ZONE 'America/New_York')::date),
        a.loaded_at
    FROM data_staging.stg_timer_entry_additions a;
END;
$$;

-- =========================================================================
-- 3. Schema metadata
-- =========================================================================
INSERT INTO agent.schema_metadata (schema_name, table_name, column_name, description)
VALUES
    ('data_staging', 'stg_timer_entry_additions', 'entry_id',
     '12-char md5 hex hash. Optional unique key — same algorithm as stg_timer_corrections.'),
    ('data_staging', 'stg_timer_entry_additions', 'reason',
     'Why this entry was added manually (e.g., "tech forgot to start timer").'),
    ('data_staging', 'stg_timer_entry_additions', 'added_by',
     'Email of whoever added the entry (admin/manager, not the tech).'),
    ('data_staging', 'stg_timer_entry_additions', 'run_id',
     'Sentinel UUID 00000000-0000-0000-0000-000000000001 marks rows as manual additions (not from Swift API extract).')
ON CONFLICT DO NOTHING;
